var setA = [
    "roasted",
    "microwaved",
    "sautéed",
    "cooked",
    "uncooked",
    "overcooked",
    "half-cooked",
    "badly-cooked",
    "fried",
    "deep-fried",
    "boiled",
    "half-boiled",
    "smoked",
    "burned",
    "grilled",
    "frozen",
    "chilled",
    "freeze-dried",
    "flash-frozen",
    "thawed"
];
var setB = [
    "green",
    "blue",
    "evil",
    "intriguing",
    "malicious",
    "happy",
    "sad",
    "undecided",
    "confused",
    "laughing",
    "hysterical",
    "angry",
    "maniacal",
    "creepy",
    "spooked",
    "jumping",
    "hyperactive"
];
var setC = [
    "sliced",
    "salted",
    "overseasoned",
    "unsweetened",
    "semisweetened",
    "charred",
    "chopped",
    "diced",
    "peeled",
    "aromatic",
    "spicy",
    "tasty",
    "smelly",
    "toxic",
    "radioactive"
];
var setD = [
    "avocado",
    "onion",
    "cupcake",
    "banana",
    "pear",
    "blueberry",
    "grape",
    "strawberry",
    "mango",
    "beetroot",
    "turnip",
    "eggplant",
    "carrot",
    "spinach leaf",
    "bread loaf",
    "chili",
    "brussels sprout",
    "orange"
];